"""initial

Revision ID: 7ea1262af18c
Revises: 
Create Date: 2026-03-03 16:59:36.451283

"""
from alembic import op
import sqlalchemy as sa


revision = '7ea1262af18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'colaborador', name='rol_enum'), nullable=False),
    sa.Column('avatar', sa.String(length=2), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('rendiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_rendicion', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('solicitud_fondo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estado_enum'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendiciones_id'), 'rendiciones', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rendicion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=False),
    sa.Column('ot', sa.String(length=50), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['rendicion_id'], ['rendiciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_rendiciones_id'), table_name='rendiciones')
    op.drop_table('rendiciones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
